### ISSUE TITLE
Get all published quiz route missing.

### ISSUE THREAD

**Issue by vermaaakarsh** [sayedazharsabri/Quiz-App-REST-API-TS-Mongoose#21]
At this point in the project, a user can start an exam using a quiz Id but he has no means of getting that quizId or in fact any quiz that is published by other users. This is a major breakpoint in the flow of the quiz app and needed to be resolved as without it.

**Possible solution**
Add a route getAllPublishedQuiz, which will return all the quiz published by **other** users. Also add related postman requests to the collection.

**Comment by aiman-syeda** [comment]
@vermaaakarsh Sir,
Okay, I'll try to implement it as soon as possible.
